# general
format: react
parser_tag: ["Action:"]
output_dir: eval_results
debug: false
log_level: INFO
save_dir: ./samples

# sample
## MCTS
version: mcts
image_size:
- 300
- 300
mcts:
  depth_limit: 30
  exploration_weight: 1.0
  n_iterations: 10
  num_proposed_action: 5
  enable_reflection: false
sort_action: false
num: 128
visual_perception: false
wo_image_tool_result: true
max_valid_data: 136
max_steps: 50


## env
enable_alfworld_env: false
dataset_root: false
num_threads: 1
thread_agent_mode: false
visual_som: false

# model args
model: Qwen2_5-VL-72B-Instruct-AWQ
model_name: null
base_url: null
temperature: 0.9
top_p: 0.95
repetition_penalty: 1.05
max_tokens: 1024

## eval
split: dev # train/dev/test
num_games: 140  # 3553/140/134 for train/dev/test
max_workers: 1
repeats: 1
save_intermediate: false
timeout: null
